/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InMind_Server_MicrosoftASR */

#ifndef _Included_InMind_Server_MicrosoftASR
#define _Included_InMind_Server_MicrosoftASR
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InMind_Server_MicrosoftASR
 * Method:    fromByteArr
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_InMind_Server_MicrosoftASR_fromByteArr
  (JNIEnv *, jclass, jbyteArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
